name: jicksaw
description: A new Flutter Game App.

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shake: ^2.2.0
  sensors:
  model_viewer_plus: ^1.5.0
  image: ^3.0.5
  get: ^4.6.5
  percent_indicator: ^4.2.3
  lottie: ^2.3.2
  sizer:
  carousel_slider: ^4.2.1
  cached_network_image:
  image_picker:
  animate_do:
  dropdown_button2:
  panara_dialogs: ^0.1.4
  flutter_colorpicker:
  flutter_quill:
  equatable: ^2.0.3
  flip_card: ^0.6.0
  connectivity:
  provider:
  http:
  shared_preferences:
  flutter_spinkit:
  keyboard_dismisser:
  modal_progress_hud_nsn:
  flutter_easyloading: ^3.0.5
  flutter_credit_card_container: ^0.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/dice/
    - assets/memory/
    - assets/chs/
    - assets/reward_cup/
    - assets/splash/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500
        - asset: assets/fonts/poppinsregular.ttf
    - family: Meta
      fonts:
        - asset: assets/fonts/OdisseiaTest-Regular.ttf
    - family: Meta1
      fonts:
        - asset: assets/fonts/feather_bold_by_typicalbro44_dee263c.ttf
    - family: game
      fonts:
        - asset: assets/fonts/Gumela.ttf
          weight: 700
    - family: game1
      fonts:
        - asset: assets/fonts/Play_Gaming.otf
    - family: style
      fonts:
        - asset: assets/fonts/QuickStarter.ttf
